<a href="https://colab.research.google.com/github/Shreyareddya/nlp-lab/blob/main/NLP_LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
data=pd.read_csv("/content/twitter4000.csv")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   twitts     4000 non-null   object
 1   sentiment  4000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 62.6+ KB

In [ ]:
data.count()

twitts       4000
sentiment    4000
dtype: int64

In [ ]:
data['sentiment'].value_counts()

sentiment
0    2000
1    2000
Name: count, dtype: int64

In [ ]:
data.head()

                                              twitts  sentiment
0  is bored and wants to watch a movie  any sugge...          0
1           back in miami.  waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                  ughhh i am so tired  blahhhhhhhhh          0
4  @mandagoforth me bad! It's funny though. Zacha...          0

In [ ]:
pattern=r'\s'
data['char_count']=data['twitts'].apply(lambda x:len(re.sub(pattern,'',x)))

In [ ]:
data

                                                 twitts  sentiment  char_count
0     is bored and wants to watch a movie  any sugge...          0          43
1              back in miami.  waiting to unboard ship           0          32
2     @misskpey awwww dnt dis brng bak memoriessss, ...          0          54
3                     ughhh i am so tired  blahhhhhhhhh          0          27
4     @mandagoforth me bad! It's funny though. Zacha...          0         116
...                                                 ...        ...         ...
3995                                  i just graduated           1          14
3996          Templating works; it all has to be done            1          32
3997                   mommy just brought me starbucks           1          27
3998  @omarepps watching you on a House re-run...lov...          1          45
3999  Thanks for trying to make me smile I'll make y...          1          63

[4000 rows x 3 columns]

In [ ]:
data['word_count']=data['twitts'].apply(lambda x:len(x.split()))

In [ ]:
data

,twitts,sentiment,char_count,word_count
0,is bored and wants to watch a movie any sugge...,0,43,10
1,back in miami. waiting to unboard ship,0,32,7
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12
3,ughhh i am so tired blahhhhhhhhh,0,27,6
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26
...,...,...,...,...
3995,i just graduated,1,14,3
3996,Templating works; it all has to be done,1,32,8
3997,mommy just brought me starbucks,1,27,5
3998,@omarepps watching you on a House re-run...lov...,1,45,8
3999,Thanks for trying to make me smile I'll make y...,1,63,16

In [ ]:
# Example for replacing patterns:
# data['column1'].apply(lambda x: re.sub(pattern, '', x))

# Define an email recognition pattern:
# pattern = r'\w+@\w+\.\w+' # This is for the email recognition pattern

# Example for finding patterns:
# data['twitts'].apply(lambda x: re.findall(pattern=pattern, string=x))

In [ ]:
pattern = r'\w+@\w+.\w+'

In [5]:
data['email'] = data['twitts'].apply(lambda x: re.findall(pattern = pattern, string = x))
data['email'].sample(5)

NameError: name 'data' is not defined

In [ ]:
pattern = r'\b[A-Za-z0-9._%+-]+@[A-ZA-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
data['email']=data['twitts'].apply(lambda x: re.findall(pattern = pattern, string = x))
data['email'].sample(5)